Repository internetarchive/infogami, pull requests merged in 2021-04, with the labels that each got.

#151 repr(Nothing()) —> "<Nothing>", not empty str
  infogami/infobase/client.py
Labels: Python 3

#172 Change variable 'json' --> 'json_data' to avoid conflicts
  infogami/infobase/_dbstore/save.py
  infogami/infobase/_dbstore/store.py
  infogami/infobase/client.py
  infogami/infobase/common.py
  infogami/infobase/core.py
  infogami/infobase/dbstore.py
  infogami/infobase/infobase.py
  infogami/infobase/readquery.py
  infogami/infobase/writequery.py
Labels: Lead: @dhruvmanila

#177 hotfix: re-introducing base_url into path for req
  infogami/infobase/client.py
Labels: hotfix
